package Presentacion;

import static DBUtils.DBConexion.conectar;
import static Presentacion.WindowsMethods.*;

/**
 * @author Ronald Bautista
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        super.setSize(X, Y);                             // Especifica un tamaño fijo de la ventana (1920x1024)
        super.setLocationRelativeTo(null);
        conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuDepartamento = new javax.swing.JMenuItem();
        jMenuProvincia = new javax.swing.JMenuItem();
        jMenuMunicipio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContenedorPrincipal.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout ContenedorPrincipalLayout = new javax.swing.GroupLayout(ContenedorPrincipal);
        ContenedorPrincipal.setLayout(ContenedorPrincipalLayout);
        ContenedorPrincipalLayout.setHorizontalGroup(
            ContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1057, Short.MAX_VALUE)
        );
        ContenedorPrincipalLayout.setVerticalGroup(
            ContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/64icon-Inicio.png"))); // NOI18N
        jMenu1.setText("Inicio");

        jMenuCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/32cerrar_ventana.png"))); // NOI18N
        jMenuCerrar.setText("Cerrar Pantallas");
        jMenuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCerrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/64icon-Datos.png"))); // NOI18N
        jMenu2.setText("Datos");

        jMenuDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/32icon-depto.png"))); // NOI18N
        jMenuDepartamento.setText("Departamentos");
        jMenuDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDepartamentoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuDepartamento);

        jMenuProvincia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/32icon-prov.png"))); // NOI18N
        jMenuProvincia.setText("Provincias");
        jMenuProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProvinciaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuProvincia);

        jMenuMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/32icon-munic.png"))); // NOI18N
        jMenuMunicipio.setText("Municipios");
        jMenuMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMunicipioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuMunicipio);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/64icon-reporte.png"))); // NOI18N
        jMenu3.setText("Reportes");
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/64icon-Info.png"))); // NOI18N
        jMenu4.setText("Acerca de");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContenedorPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDepartamentoActionPerformed
        // Instancia tu Clase y agrega el siguiente método aqui para abrir tu jInternalFrame
        /*
        Modelo:
            NombrejInternalFrame nombreObjeto = new NombrejInternalFrame();
            openWindow(nombreObjeto);
        Ejemplo:
         */
        FrmDepartamentos ventanaDepartamento = new FrmDepartamentos();
        openWindow(ventanaDepartamento);
    }//GEN-LAST:event_jMenuDepartamentoActionPerformed

    private void jMenuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarActionPerformed
        cerrarVentanasExistentes();
    }//GEN-LAST:event_jMenuCerrarActionPerformed

    private void jMenuProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProvinciaActionPerformed
        // Instancia tu Clase y agrega el siguiente método aqui para abrir tu jInternalFrame
        /*
        Modelo:
            NombrejInternalFrame nombreObjeto = new NombrejInternalFrame();
            openWindow(nombreObjeto);
        Ejemplo:
            JInternalFramePrueba ventanaPrueba = new JInternalFramePrueba();
            openWindow(ventanaPrueba);
         */
        FrmProvincias ventanaProvincias = new FrmProvincias();
        openWindow(ventanaProvincias);
    }//GEN-LAST:event_jMenuProvinciaActionPerformed

    private void jMenuMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMunicipioActionPerformed
        // Instancia tu Clase y agrega el siguiente método aqui para abrir tu jInternalFrame
        /*
        Modelo:
            NombrejInternalFrame nombreObjeto = new NombrejInternalFrame();
            openWindow(nombreObjeto);
        Ejemplo:
            JInternalFramePrueba ventanaPrueba = new JInternalFramePrueba();
            openWindow(ventanaPrueba);
         */
        FrmMunicipios ventanaMunicipio = new FrmMunicipios();
        openWindow(ventanaMunicipio);
    }//GEN-LAST:event_jMenuMunicipioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane ContenedorPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCerrar;
    private javax.swing.JMenuItem jMenuDepartamento;
    private javax.swing.JMenuItem jMenuMunicipio;
    private javax.swing.JMenuItem jMenuProvincia;
    // End of variables declaration//GEN-END:variables
}
